import express from'express';import{createServer}from'node:http';import{WebSocketServer}from'ws';import{fileURLToPath}from'node:url';import{dirname,join}from'node:path';import{mkdir,readFile,writeFile}from'node:fs/promises';import{homedir}from'node:os';import{randomUUID}from'node:crypto';import{createDriver}from'./ptz/factory.js';import type{Camera,Direction}from'./ptz/types.js';
const app=express(),server=createServer(app),wss=new WebSocketServer({server,path:'/ws'}),here=dirname(fileURLToPath(import.meta.url)),webRoot=join(here,'..','web');app.use(express.json());app.use(express.static(webRoot));app.get('/',(_q,r)=>r.redirect('/obs'));app.get('/obs',(_q,r)=>r.sendFile(join(webRoot,'index.html')));app.get('/api/health',(_q,r)=>r.json({ok:true,version:'0.5.0'}));
type PresetMeta={name:string;saved:boolean};type Store={version:number;cameras:Camera[];presets:Record<string,Record<string,PresetMeta>>};
const dataDir=process.platform==='win32'?join(process.env.APPDATA||join(homedir(),'AppData','Roaming'),'PTZ Control Web'):join(process.env.XDG_CONFIG_HOME||join(homedir(),'.config'),'ptz-control-web'),dataFile=join(dataDir,'config.json');
let store:Store={version:1,cameras:[],presets:{}};const cameras=new Map<string,Camera>();
async function saveStore(){await mkdir(dataDir,{recursive:true});store.cameras=[...cameras.values()];await writeFile(dataFile,JSON.stringify(store,null,2),'utf8')}
async function loadStore(){try{const raw=JSON.parse(await readFile(dataFile,'utf8')) as Partial<Store>;store={version:1,cameras:Array.isArray(raw.cameras)?raw.cameras:[],presets:raw.presets||{}};for(const c of store.cameras)cameras.set(c.id,c)}catch(e:any){if(e?.code!=='ENOENT')console.error('Could not load persistent config:',e)}}
app.get('/api/storage',(_q,r)=>r.json({path:dataFile}));
app.get('/api/presets/:id', (q,r)=>r.json(store.presets[q.params.id]||{}));
app.post('/api/presets/:id',async(q,r)=>{try{store.presets[q.params.id]=q.body&&typeof q.body==='object'?q.body:{};await saveStore();r.sendStatus(204)}catch(e){r.status(500).json({error:(e as Error).message})}});
app.get('/api/cameras',(_q,r)=>r.json([...cameras.values()]));app.delete('/api/cameras/:id',async(q,r)=>{try{const id=q.params.id;if(!cameras.has(id))return r.status(404).json({error:'Camera not found'});cameras.delete(id);delete store.presets[id];await saveStore();r.sendStatus(204)}catch(e){r.status(500).json({error:(e as Error).message})}});app.post('/api/cameras',(q,r)=>{const c=q.body as Partial<Camera>;if(!c.name)return r.status(400).json({error:'name is required'});if(c.protocol==='visca-serial'&&!c.serialPort)return r.status(400).json({error:'serialPort is required'});if((c.protocol??'visca-udp')!=='visca-serial'&&!c.host)return r.status(400).json({error:'host is required'});const camera:Camera={id:c.id||randomUUID(),name:c.name,host:c.host,port:Number(c.port??(c.protocol==='visca-tcp'?5678:52381)),protocol:c.protocol??'visca-udp',online:true,maxSpeed:Number(c.maxSpeed??20),presetCount:Number(c.presetCount??24),invertPan:!!c.invertPan,invertTilt:!!c.invertTilt,username:c.username,password:c.password,serialPort:c.serialPort,baudRate:Number(c.baudRate??9600),viscaIpFraming:c.viscaIpFraming!==false,useSequenceNumbers:c.useSequenceNumbers!==false};cameras.set(camera.id,camera);saveStore().then(()=>r.status(201).json(camera)).catch(e=>r.status(500).json({error:e.message}))});
function driver(id:string){const c=cameras.get(id);if(!c)throw new Error('Camera not found');return createDriver(c)}
function companionCamera(selector:string){const list=[...cameras.values()];const byId=cameras.get(selector);if(byId)return byId;const n=Number(selector);if(Number.isInteger(n)&&n>=1&&n<=list.length)return list[n-1];const byName=list.find(c=>c.name.toLowerCase()===decodeURIComponent(selector).toLowerCase());if(byName)return byName;throw new Error('Camera not found')}
function companionDirection(c:Camera,d:Direction){if(c.invertPan)d=({'left':'right','right':'left','up-left':'up-right','up-right':'up-left','down-left':'down-right','down-right':'down-left'} as Partial<Record<Direction,Direction>>)[d]||d;if(c.invertTilt)d=({'up':'down','down':'up','up-left':'down-left','up-right':'down-right','down-left':'up-left','down-right':'up-right'} as Partial<Record<Direction,Direction>>)[d]||d;return d}
function companionError(r:any,e:unknown){r.status(400).json({ok:false,error:(e as Error).message})}function broadcastCompanion(data:Record<string,unknown>){const msg=JSON.stringify({type:'companion-command',...data});for(const ws of wss.clients)if(ws.readyState===1)ws.send(msg)}
app.get('/api/companion',(_q,r)=>r.json({ok:true,name:'PTZ Control Web — by Culto em Off',version:'0.5.0',base:'/api/companion',cameraSelector:'Use camera UUID, exact name, or 1-based camera number',presetNumbering:'0-based'}));
app.get('/api/companion/cameras',(_q,r)=>r.json([...cameras.values()].map((c,index)=>({number:index+1,id:c.id,name:c.name,protocol:c.protocol,online:c.online,presets:store.presets[c.id]||{}}))));
app.post('/api/companion/camera/:camera/move/:direction',async(q,r)=>{try{const c=companionCamera(q.params.camera),allowed:Direction[]=['up','down','left','right','up-left','up-right','down-left','down-right','stop'],raw=q.params.direction as Direction;if(!allowed.includes(raw))throw new Error('Invalid direction');const d=companionDirection(c,raw),speed=Math.max(1,Math.min(Number(q.query.speed??8),c.maxSpeed??20));await createDriver(c).move(d,speed,speed);broadcastCompanion({cameraId:c.id,action:'move',value:raw});r.json({ok:true,camera:c.name,action:'move',direction:raw,speed})}catch(e){companionError(r,e)}});
app.post('/api/companion/camera/:camera/zoom/:direction',async(q,r)=>{try{const c=companionCamera(q.params.camera),direction=q.params.direction as'in'|'out'|'stop';if(!['in','out','stop'].includes(direction))throw new Error('Invalid zoom direction');const speed=Math.max(1,Math.min(Number(q.query.speed??3),7));await createDriver(c).zoom(direction,speed);broadcastCompanion({cameraId:c.id,action:'zoom',value:direction});r.json({ok:true,camera:c.name,action:'zoom',direction,speed})}catch(e){companionError(r,e)}});
app.post('/api/companion/camera/:camera/focus/:mode',async(q,r)=>{try{const c=companionCamera(q.params.camera),mode=q.params.mode as'auto'|'near'|'far'|'stop';if(!['auto','near','far','stop'].includes(mode))throw new Error('Invalid focus mode');await createDriver(c).focus(mode);broadcastCompanion({cameraId:c.id,action:'focus',value:mode});r.json({ok:true,camera:c.name,action:'focus',mode})}catch(e){companionError(r,e)}});
app.post('/api/companion/camera/:camera/home',async(q,r)=>{try{const c=companionCamera(q.params.camera);await createDriver(c).home();broadcastCompanion({cameraId:c.id,action:'home'});r.json({ok:true,camera:c.name,action:'home'})}catch(e){companionError(r,e)}});
app.post('/api/companion/camera/:camera/preset/:preset/recall',async(q,r)=>{try{const c=companionCamera(q.params.camera),preset=Number(q.params.preset);if(!Number.isInteger(preset)||preset<0||(c.presetCount!=null&&preset>=c.presetCount))throw new Error('Invalid preset');await createDriver(c).recallPreset(preset);broadcastCompanion({cameraId:c.id,action:'preset-recall',preset});r.json({ok:true,camera:c.name,action:'preset-recall',preset})}catch(e){companionError(r,e)}});
app.post('/api/companion/camera/:camera/preset/:preset/save',async(q,r)=>{try{const c=companionCamera(q.params.camera),preset=Number(q.params.preset);if(!Number.isInteger(preset)||preset<0||(c.presetCount!=null&&preset>=c.presetCount))throw new Error('Invalid preset');await createDriver(c).savePreset(preset);broadcastCompanion({cameraId:c.id,action:'preset-save',preset});r.json({ok:true,camera:c.name,action:'preset-save',preset})}catch(e){companionError(r,e)}});
app.post('/api/cameras/:id/move',async(q,r)=>{try{const c=cameras.get(q.params.id);let d=q.body.direction as Direction;if(c?.invertPan){d=({'left':'right','right':'left','up-left':'up-right','up-right':'up-left','down-left':'down-right','down-right':'down-left'} as any)[d]||d}if(c?.invertTilt){d=({'up':'down','down':'up','up-left':'down-left','up-right':'down-right','down-left':'up-left','down-right':'up-right'} as any)[d]||d}const max=c?.maxSpeed??20;await driver(q.params.id).move(d,Math.min(Number(q.body.panSpeed??8),max),Math.min(Number(q.body.tiltSpeed??8),max));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
app.post('/api/cameras/:id/focus',async(q,r)=>{try{await driver(q.params.id).focus(q.body.mode);r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});app.post('/api/cameras/:id/zoom',async(q,r)=>{try{await driver(q.params.id).zoom(q.body.direction,Number(q.body.speed??3));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});app.post('/api/cameras/:id/home',async(q,r)=>{try{await driver(q.params.id).home();r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});app.post('/api/cameras/:id/presets/:preset/recall',async(q,r)=>{try{await driver(q.params.id).recallPreset(Number(q.params.preset));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});app.post('/api/cameras/:id/presets/:preset/save',async(q,r)=>{try{await driver(q.params.id).savePreset(Number(q.params.preset));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
wss.on('connection',ws=>ws.send(JSON.stringify({type:'hello',version:'0.5.0'})));loadStore().then(()=>server.listen(8765,'127.0.0.1',()=>{console.log('PTZ Control Web — by Culto em Off: http://127.0.0.1:8765/obs');console.log('Persistent data:',dataFile)})).catch(e=>{console.error(e);process.exitCode=1});
