import express from 'express';import{createServer}from'node:http';import{WebSocketServer}from'ws';import{fileURLToPath}from'node:url';import{dirname,join}from'node:path';import{ViscaUdpDriver}from'./ptz/viscaUdp.js';import type{Camera,Direction}from'./ptz/types.js';
const app=express(),server=createServer(app),wss=new WebSocketServer({server,path:'/ws'}),here=dirname(fileURLToPath(import.meta.url)),webRoot=join(here,'..','web');
app.use(express.json());app.use(express.static(webRoot));app.get('/',(_q,r)=>r.redirect('/obs'));app.get('/obs',(_q,r)=>r.sendFile(join(webRoot,'index.html')));app.get('/api/health',(_q,r)=>r.json({ok:true,version:'0.2.0'}));
const cameras=new Map<string,Camera>();app.get('/api/cameras',(_q,r)=>r.json([...cameras.values()]));app.post('/api/cameras',(q,r)=>{const c=q.body as Partial<Camera>;if(!c.name||!c.host)return r.status(400).json({error:'name and host are required'});const camera:Camera={id:c.id??crypto.randomUUID(),name:c.name,host:c.host,port:c.port??52381,protocol:c.protocol??'visca-udp',online:true};cameras.set(camera.id,camera);r.status(201).json(camera)});
function driver(id:string){const c=cameras.get(id);if(!c)throw new Error('Camera not found');if(c.protocol!=='visca-udp')throw new Error('Protocol not implemented yet');return new ViscaUdpDriver(c.host,c.port)}
app.post('/api/cameras/:id/move',async(q,r)=>{try{await driver(q.params.id).move(q.body.direction as Direction,Number(q.body.panSpeed??8),Number(q.body.tiltSpeed??8));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
app.post('/api/cameras/:id/zoom',async(q,r)=>{try{await driver(q.params.id).zoom(q.body.direction,Number(q.body.speed??3));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
app.post('/api/cameras/:id/home',async(q,r)=>{try{await driver(q.params.id).home();r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
app.post('/api/cameras/:id/presets/:preset/recall',async(q,r)=>{try{await driver(q.params.id).recallPreset(Number(q.params.preset));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
app.post('/api/cameras/:id/presets/:preset/save',async(q,r)=>{try{await driver(q.params.id).savePreset(Number(q.params.preset));r.sendStatus(204)}catch(e){r.status(400).json({error:(e as Error).message})}});
wss.on('connection',ws=>ws.send(JSON.stringify({type:'hello',version:'0.2.0'})));server.listen(8765,'127.0.0.1',()=>console.log('PTZ Control Dock: http://127.0.0.1:8765/obs'));
