const $=s=>document.querySelector(s),api=async(path,body)=>fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
let active=localStorage.activeCamera||'',cameras=[],editingPreset=1;const count=()=>Number(localStorage.presetCount||8),key=id=>`presets:${id}`,meta=()=>JSON.parse(localStorage.getItem(key(active))||'{}'),saveMeta=m=>localStorage.setItem(key(active),JSON.stringify(m));
function renderPresets(){const box=$('#presets'),m=meta();box.innerHTML='';for(let i=1;i<=count();i++){const p=m[i],b=document.createElement('button');b.className='preset '+(p?.saved?'saved':'');b.innerHTML=`<b>${p?.name||i}</b><small>${p?.saved?'● SALVA':'○ VAZIA'}</small>`;b.onclick=()=>p?.saved&&active&&api(`/api/cameras/${active}/presets/${i}/recall`,{});b.oncontextmenu=e=>{e.preventDefault();editingPreset=i;$('#presetTitle').textContent=`Memória ${i}`;$('#presetName').value=p?.name||'';$('#presetDialog').showModal()};box.appendChild(b)}}
function renderCameras(){const box=$('#cameras');box.innerHTML='';$('#cameraCount').textContent=`${cameras.length} conectada(s)`;cameras.forEach(c=>{const b=document.createElement('button');b.className='cameraItem '+(c.id===active?'active':'');b.innerHTML=`<span><b>▣ ${c.name}</b><small>${c.host} • ${c.protocol}</small></span><span class="dot">●</span>`;b.onclick=()=>{active=c.id;localStorage.activeCamera=active;renderCameras();renderPresets();updateName()};box.appendChild(b)});updateName()}
function updateName(){const c=cameras.find(x=>x.id===active);$('#activeName').textContent=c?c.name:'Nenhuma câmera'}async function load(){cameras=await(await api('/api/cameras')).json();if(!cameras.some(c=>c.id===active))active=cameras[0]?.id||'';renderCameras();renderPresets();$('#presetCount').value=String(count());$('#presetPosition').value=localStorage.presetPosition||'bottom';applyLayout()}
function applyLayout(){const side=(localStorage.presetPosition||'bottom')==='right';$('#workspace').classList.toggle('right',side)}
const speed=()=>Number($('#speed').value),stopMove=()=>active&&api(`/api/cameras/${active}/move`,{direction:'stop',panSpeed:speed(),tiltSpeed:speed()});document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();active&&api(`/api/cameras/${active}/move`,{direction:b.dataset.move,panSpeed:speed(),tiltSpeed:speed()})};b.onpointerup=b.onpointercancel=b.onpointerleave=stopMove});document.querySelectorAll('[data-zoom]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();active&&api(`/api/cameras/${active}/zoom`,{direction:b.dataset.zoom,speed:3})};const stop=()=>active&&api(`/api/cameras/${active}/zoom`,{direction:'stop',speed:0});b.onpointerup=b.onpointercancel=b.onpointerleave=stop});
$('#home').onclick=()=>active&&api(`/api/cameras/${active}/home`,{});$('#settings').onclick=()=>$('#settingsDialog').showModal();$('#scan').onclick=()=>alert('A descoberta automática NDI/ONVIF será conectada ao botão nesta etapa do projeto.');$('#presetCount').onchange=e=>{localStorage.presetCount=e.target.value;renderPresets()};$('#presetPosition').onchange=e=>{localStorage.presetPosition=e.target.value;applyLayout()};
$('#savePosition').onclick=async()=>{if(!active)return;await api(`/api/cameras/${active}/presets/${editingPreset}/save`,{});const m=meta();m[editingPreset]={name:$('#presetName').value.trim()||`Posição ${editingPreset}`,saved:true};saveMeta(m);$('#presetDialog').close();renderPresets()};$('#clearPreset').onclick=()=>{const m=meta();delete m[editingPreset];saveMeta(m);$('#presetDialog').close();renderPresets()};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#about').onclick=()=>$('#aboutDialog').showModal();
const themes=['auto','dark','light'];let theme=localStorage.theme||'auto';function apply(){document.documentElement.dataset.theme=theme==='auto'?'':theme;localStorage.theme=theme}apply();$('#theme').onclick=()=>{theme=themes[(themes.indexOf(theme)+1)%themes.length];apply()};load();